version = 0.1

[default.deploy.parameters]
stack_name = "aws-serverless-order-processing"
resolve_s3 = true
s3_prefix = "aws-serverless-order-processing"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "Environment=dev NotificationEmail=''"

